# Generated by Django 6.0.4 on 2026-05-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaivarity',
            name='type',
            field=models.CharField(choices=[('MS', 'Masala'), ('GR', 'GINGER'), ('KL', 'KIWI'), ('PL', 'PLAIN'), ('EL', 'ELACHI')], max_length=2),
        ),
    ]
