# Generated by Django 6.0.5 on 2026-06-02 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaireview',
            name='chai',
        ),
        migrations.RemoveField(
            model_name='chaireview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='store',
            name='chai_varieties',
        ),
        migrations.CreateModel(
            name='ChaiReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chai.chaivarity')),
            ],
        ),
        migrations.DeleteModel(
            name='ChaiCertificate',
        ),
        migrations.DeleteModel(
            name='ChaiReview',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
