# Generated by Django 6.0.5 on 2026-06-02 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0004_remove_chaireview_chai_remove_chaireview_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaireviews',
            name='name',
            field=models.CharField(default='No name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaireviews',
            name='chai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='chai.chaivarity'),
        ),
    ]
