# Generated by Django 6.0.4 on 2026-05-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_alter_chaivarity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivarity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
