# Generated by Django 6.0.5 on 2026-05-31 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Card_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcards',
            old_name='Image',
            new_name='image',
        ),
    ]
